spring:
  datasource:
    url: jdbc:mysql://119.29.239.91:3306/baojie?serverTimezone=CST&useSSL=false&allowMultiQueries=true
    username: root
    password: Mysql615243!
mybatis:
  mapper-locations: classpath:mapper/*.xml