spring:
  datasource:
    url: jdbc:mysql://47.100.253.25:3306/baojie?serverTimezone=CST&useSSL=false&allowMultiQueries=true
    username: root
    password: Mysql615243!
mybatis:
  mapper-locations: classpath:mapper/*.xml